{{- if or (and (not .Release.IsInstall) (not .Release.IsUpgrade)) (and .Values.cert.key .Values.cert.crt) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-certs
  namespace: {{ .Release.Namespace }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  root.key: {{ .Values.cert.key }}
  server.crt: {{ .Values.cert.crt }}
{{- end }}
