apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-crd-upgrade
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-upgrade,pre-install
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded