{{- if .Values.extensions.cache.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-extensions-cache
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
rules:
- apiGroups: ["", "apps"]
  resources:
  - serviceaccounts
  - statefulsets
  verbs:
  - get
  - patch
  - update
  resourceNames:
  - {{ .Release.Name }}-extensions-cache
- apiGroups: [""]
  resources:
  - pods
  verbs:
  - delete
  resourceNames:
  - {{ .Release.Name }}-extensions-cache-0
{{- end }}
