{{- if or (and (not .Release.IsInstall) (not .Release.IsUpgrade)) (and .Values.cert.key .Values.cert.crt) }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
webhooks:
  - name: sgcluster.{{ .Release.Name }}.{{ .Release.Namespace }}
    {{- if (semverCompare ">1.12-0" .Capabilities.KubeVersion.GitVersion) }}
    sideEffects: None
    {{- end }}
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["stackgres.io"]
        apiVersions: ["*"]
        resources: ["sgclusters"]
    failurePolicy: Fail
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ .Release.Name }}
        path: '/stackgres/validation/sgcluster'
      caBundle: {{ .Values.cert.crt }}
    admissionReviewVersions: ["v1beta1"]
  - name: sgpgconfig.{{ .Release.Name }}.{{ .Release.Namespace }}
    {{- if (semverCompare ">1.12-0" .Capabilities.KubeVersion.GitVersion) }}
    sideEffects: None
    {{- end }}
    rules:
      - operations: ["CREATE", "UPDATE", "DELETE"]
        apiGroups: ["stackgres.io"]
        apiVersions: ["*"]
        resources: ["sgpgconfigs"]
    failurePolicy: Fail
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ .Release.Name }}
        path: '/stackgres/validation/sgpgconfig'
      caBundle: {{ .Values.cert.crt }}
    admissionReviewVersions: ["v1beta1"]
  - name: sgpoolconfig.{{ .Release.Name }}.{{ .Release.Namespace }}
    {{- if (semverCompare ">1.12-0" .Capabilities.KubeVersion.GitVersion) }}
    sideEffects: None
    {{- end }}
    rules:
      - operations: ["CREATE", "UPDATE", "DELETE"]
        apiGroups: ["stackgres.io"]
        apiVersions: ["*"]
        resources: ["sgpoolconfigs"]
    failurePolicy: Fail
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ .Release.Name }}
        path: '/stackgres/validation/sgpoolconfig'
      caBundle: {{ .Values.cert.crt }}
    admissionReviewVersions: ["v1beta1"]
  - name: sginstanceprofile.{{ .Release.Name }}.{{ .Release.Namespace }}
    {{- if (semverCompare ">1.12-0" .Capabilities.KubeVersion.GitVersion) }}
    sideEffects: None
    {{- end }}
    rules:
      - operations: ["CREATE", "UPDATE", "DELETE"]
        apiGroups: ["stackgres.io"]
        apiVersions: ["*"]
        resources: ["sginstanceprofiles"]
    failurePolicy: Fail
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ .Release.Name }}
        path: '/stackgres/validation/sginstanceprofile'
      caBundle: {{ .Values.cert.crt }}
    admissionReviewVersions: ["v1beta1"]
  - name: sgbackupconfig.{{ .Release.Name }}.{{ .Release.Namespace }}
    {{- if (semverCompare ">1.12-0" .Capabilities.KubeVersion.GitVersion) }}
    sideEffects: None
    {{- end }}
    rules:
      - operations: ["CREATE", "UPDATE", "DELETE"]
        apiGroups: ["stackgres.io"]
        apiVersions: ["*"]
        resources: ["sgbackupconfigs"]
    failurePolicy: Fail
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ .Release.Name }}
        path: '/stackgres/validation/sgbackupconfig'
      caBundle: {{ .Values.cert.crt }}
    admissionReviewVersions: ["v1beta1"]
  - name: sgbackup.{{ .Release.Name }}.{{ .Release.Namespace }}
    {{- if (semverCompare ">1.12-0" .Capabilities.KubeVersion.GitVersion) }}
    sideEffects: None
    {{- end }}
    rules:
      - operations: ["CREATE", "UPDATE", "DELETE"]
        apiGroups: ["stackgres.io"]
        apiVersions: ["*"]
        resources: ["sgbackups"]
    failurePolicy: Fail
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ .Release.Name }}
        path: '/stackgres/validation/sgbackup'
      caBundle: {{ .Values.cert.crt }}
    admissionReviewVersions: ["v1beta1"]
  - name: sgdistributedlogs.{{ .Release.Name }}.{{ .Release.Namespace }}
    {{- if (semverCompare ">1.12-0" .Capabilities.KubeVersion.GitVersion) }}
    sideEffects: None
    {{- end }}
    rules:
      - operations: ["CREATE", "UPDATE", "DELETE"]
        apiGroups: ["stackgres.io"]
        apiVersions: ["*"]
        resources: ["sgdistributedlogs"]
    failurePolicy: Fail
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ .Release.Name }}
        path: '/stackgres/validation/sgdistributedlogs'
      caBundle: {{ .Values.cert.crt }}
    admissionReviewVersions: ["v1beta1"]
  - name: sgdbops.{{ .Release.Name }}.{{ .Release.Namespace }}
    {{- if (semverCompare ">1.12-0" .Capabilities.KubeVersion.GitVersion) }}
    sideEffects: None
    {{- end }}
    rules:
      - operations: ["CREATE", "UPDATE", "DELETE"]
        apiGroups: ["stackgres.io"]
        apiVersions: ["*"]
        resources: ["sgdbops"]
    failurePolicy: Fail
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ .Release.Name }}
        path: '/stackgres/validation/sgdbops'
      caBundle: {{ .Values.cert.crt }}
    admissionReviewVersions: ["v1beta1"]
{{- end }}