{{- if and .Values.deploy.restapi .Values.authentication }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.restapi.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
    api.stackgres.io/auth: user
type: Opaque
data:
  k8sUsername: {{ .Values.authentication.user | b64enc | quote }}
  {{- if .Values.authentication.password }}
  password: {{ (printf "%s%s" .Values.authentication.user .Values.authentication.password) | sha256sum | b64enc | quote }}
  {{- else }}
  {{- $password := randAlphaNum 40 }}
  password: {{ (printf "%s%s" .Values.authentication.user $password) | sha256sum | b64enc | quote }}
  clearPassword: {{ $password | b64enc | quote }}
  {{- end }}
{{- end }}
