---
# Source: stackgres-operator/templates/cr-updater-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: "stackgres-operator-cr-updater"
  namespace: stackgres
  labels:
    app: stackgres-operator-init
    job: cr-updater
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "50"    
spec:
  template:
    metadata:
      labels:
        app: stackgres-operator-init
        job: cr-updater
    spec:
      serviceAccountName: stackgres-operator-init
      restartPolicy: OnFailure
      terminationGracePeriodSeconds: 0
      securityContext:
        runAsNonRoot: true
        fsGroup: 1000
      containers:
      - name: cr-updater
        image: "quay.io/stackgres/jobs:1.5.0"
        imagePullPolicy: "IfNotPresent"
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
        env:
          - name: OPERATOR_NAME
            value: "stackgres-operator"
          - name: OPERATOR_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: CR_UPDATER
            value: "true"
