---
# Source: stackgres-operator/templates/webapi-authentication-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: stackgres-restapi
  namespace: stackgres
  annotations:
    meta.helm.sh/release-name: stackgres-operator
    meta.helm.sh/release-namespace: stackgres
  labels:
    app.kubernetes.io/managed-by: Helm
    api.stackgres.io/auth: user
type: Opaque
data:
  k8sUsername: "YWRtaW4="
  password: "YzBmODk0NmFlNDY4NDc3YmI2N2MwNjc0OTViMGM4OTdjNGVkNTNjZTc0MTQ5MmQ5ZjAzNzczNWY3YWE1YWUyMw=="
  clearPassword: "d0pTSTRXNmtPOFhGQXFaQmxtOWlVYm5CN3lOODIzQ21tRk9XYkNRRw=="
